### 创建矩阵

In [2]:
import torch
a = torch.arange(20).reshape(5,4)

### 矩阵的转置

In [3]:
a.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 两个矩阵按元素的乘法称为 哈达玛积 （Hadamard product）

In [4]:
b = a.clone()
a * b

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

### sum of elements

In [6]:
# sum of the elements
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [7]:
a.sum(axis = 0), a.sum(axis = [0,1])

(tensor([40, 45, 50, 55]), tensor(190))

### keep the dimension while do sum or mean

In [10]:
sum_A = a.sum(axis = 1, keepdims = True)
a, sum_A

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 6],
         [22],
         [38],
         [54],
         [70]]))

In [13]:
a / sum_A # broadcasting

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

### 点积是相同位置的按元素乘积的和

In [15]:
y = torch.ones(4, dtype = torch.float32)
x, y , torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

### 我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [16]:
torch.sum(x * y)

tensor(6.)

In [30]:
# matrix multiplication
a.shape, x.shape, torch.mv(a.float(),x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### L2范数是向量元素平方和的平方根

In [31]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)