In [3]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

### 梯度存储

In [4]:
x.requires_grad_(True) #等价于 x = torch.arange(4.0, requires_grad = True)
x.grad

In [5]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

### 通过调用反向传播函数来自动计算y关于x每个分量的梯度

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

### 在默认情况下，pytorch会积累梯度，我们需要清楚之前的值

In [9]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和

In [10]:
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [11]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])